version: '3.8'

services:
  backend:
    build: .
    container_name: backend-service
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - fastapi
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - app-network

  fastapi:
    build: ./fastAPI
    container_name: fastapi-service
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - ./fastAPI:/app
    networks:
      - app-network

  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
